name: Deploy Painel Protegido

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Criptografar com Senha
      run: |
        npm install -g pagecrypt
        # Substitua a palavra MINHASENHA123 abaixo pela senha secreta que você quiser usar
        pagecrypt index.html index.html "S@ntidad3"

    - name: Upload para o GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
